### ISSUE TITLE
rotation_interval config

### ISSUE THREAD

**Issue by jmnote** [kuoss/lethe#61]
### What would you like to be added?

rotation_interval config 도입

### Why is this needed?

```yaml
rotation_interval: 20m
retention:
  time: 1d
  size: 100m
storage:
  rootdirectory: /data/log
  driver: filesystem
```
